name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Update and Install Make
      run: |
          sudo apt update
          sudo apt install -y make
      working-directory: ./api
    - name: Build API with Make
      run: |
          make up
          make install
          make mig
      working-directory: ./api


    - name: Run Playwright tests
      run: |
            npx playwright test 2.automation-tests/e2e/
            npx playwright test 2.automation-tests/api/
       
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

    - name: Parar API Server
      if: always()
      run: |
        cd api
        make down
